### ISSUE TITLE
छलफल : यो मंचको नाम के राख्ने?

### ISSUE THREAD

**Issue by ayys** [SiyaOrg/e-sawal#1]

**Comment by ayys** [comment]
मैले सोचेको एउटा नाम - _छलफल मंच_ @akhil123pp

**Comment by bravegurkha** [comment]
kunchai munch ko kura garnu vako dai ?

**Comment by bravegurkha** [comment]
@ayys kun yo project ko naam chhalfal manch ?

**Comment by ayys** [comment]
@bravegurkha e aah hai. tara project to naam ma ta "---" matra cha ni. Tyo change garnu paryo :+1:

**Comment by bravegurkha** [comment]
@ayys ah dai change vaisakyo hai. :smile:
